// Review vocabulary and interface map; domains are logical boundaries, not
// a claim that each has already been deployed as a separate service.
export const domains = [
  {id:'provider',name:'제공자·전략',en:'Provider / Strategy',owns:'전략의 정체성, 제공자 권한, 비공개 운용 판단',input:'제공자 서명, 전략 이름·설명, private alpha',output:'전략 등록, strategyId에 귀속된 운용 요청',up:['privacy'],down:['authorization'],implementation:'전략 등록·서명 주문 구현',gap:'Private alpha를 포지션 목표와 주문으로 자동 변환하는 경로는 미구현. 현재는 제공자가 주문 방향·금액을 직접 서명합니다.',source:'src/sleeves/runtime.js · REGISTER / ORDER',rules:['같은 제공자도 여러 전략을 가질 수 있습니다.','제공자의 판단은 해당 전략에만 적용합니다.','다른 제공자의 alpha와 합성하지 않습니다.'],fields:[['provider','전략을 소유하는 서명 지갑'],['strategyId','경제적으로 독립적인 전략 계정'],['private alpha','설계상 비공개 입력. 현재는 서명 주문으로 대체'],['side / asset / amount','현재 실제로 받는 주문 입력']]},
  {id:'investor',name:'투자자·배정',en:'Investor / Allocation',owns:'전략 선택, 투자 금액, 배정·환매 의사',input:'투자자 지갑 서명, 선택한 strategyId, 금액',output:'예치 요청 / 해당 전략 units의 환매 요청',up:['ledger'],down:['authorization','vault'],implementation:'전략별 배정·환매 구현',gap:'브라우저 지갑 승인 UX는 외부 지갑 모드에서 검토해야 합니다. 로컬 모드는 테스트 키로 서명을 생성합니다.',source:'src/web/Strategies.jsx · signed / finishDeposit',rules:['투자자는 Vault 전체 지분을 사지 않습니다.','한 투자자가 여러 전략에 배정할 수 있습니다.','한 전략의 환매가 다른 전략의 지분을 소각하지 않습니다.'],fields:[['signer','배정·환매 권리의 소유자'],['strategyId','자본과 권리를 귀속할 전략'],['amount','해당 전략에 배정할 테스트 토큰 수량'],['units','선택한 전략의 지분 수량']]},
  {id:'authorization',name:'권한·요청',en:'Authorization / Intent',owns:'서명 검증, 도메인 바인딩, 중복 방지, 처리 중 요청',input:'서명된 REGISTER / ALLOCATE / ORDER / REDEEM / PAY_PROVIDER',output:'승인된 전략별 명령 또는 거절 사유',up:['provider','investor'],down:['ledger','vault'],implementation:'서명·nonce·만료·요청 복구 구현',gap:'권한 검증과 계약 호출은 운영자 프로세스에서 수행합니다. 컨트랙트가 원문 private alpha를 직접 검증하는 구조는 아닙니다.',source:'src/sleeves/runtime.js · authenticate / submitLocked / process',rules:['chainId와 Vault 주소가 다르면 거절합니다.','제공자만 자기 전략의 주문을 낼 수 있습니다.','동일 nonce는 재사용할 수 없습니다.','pending 요청이 있으면 다른 변경을 막고 같은 요청으로 복구합니다.'],fields:[['domain / chainId / vault','다른 서비스나 체인에서의 서명 재사용 방지'],['signer / signature','요청 주체와 서명'],['nonce / expiresAt','중복·만료 검사'],['pending intent','외부 거래와 장부 반영 사이의 복구 단위']]},
  {id:'ledger',name:'비공개 장부',en:'Private Strategy Ledger',owns:'전략별 현금·포지션·부채·units·투자자 권리·주문 귀속',input:'확인된 예치·체결·정산·출금 결과',output:'Strategy Equity, Investor Claim, Provider Accrual, 주문의 전략 귀속',up:['settlement','authorization'],down:['vault','investor','privacy'],implementation:'독립 전략 회계·귀속 구현',gap:'현재 운영자는 장부 파일을 읽을 수 있습니다. TEE의 비공개 저장·계산 보호는 연결되지 않았습니다.',source:'src/sleeves/ledger.js · SleeveLedger',rules:['다른 전략의 현금·보유 자산을 사용할 수 없습니다.','Strategy Equity = Investor Claims 합계 + Provider Accrual','Vault Equity = Strategy Equity 합계 + Protocol Accruals','strategyId ↔ orderId의 연결은 공개 체인에 보내지 않습니다.'],fields:[['cash / positions / shorts','전략별 경제적 자산과 부채'],['investors / units','투자자별 전략 지분'],['orders','주문 → 전략 귀속'],['providerAccrual / highWater','보수 권리와 지분가치 고점']]},
  {id:'vault',name:'공동 Vault',en:'Omnibus Custody / Execution',owns:'실제 토큰 보관, 하나의 실행 주소, 자금 입출금',input:'ERC20 예치, 승인된 opaque 주문 ID, 출금 명령',output:'Deposit / Committed / Fill / Withdrawal 이벤트',up:['authorization','ledger','investor'],down:['market','settlement'],implementation:'새 공동 Vault 계약 배포·검증',gap:'운영자에게 실행·출금 권한이 있습니다. TEE 승인이나 운영자 권한을 대체하는 검증은 아직 적용하지 않았습니다.',source:'contracts/sleeves/OmnibusVault.sol · OmnibusVault',rules:['모든 전략의 실제 토큰은 동일한 Vault에 보관합니다.','Vault는 공동 투자상품 지분을 발행하지 않습니다.','체인에는 provider·strategyId 대신 opaque 요청 ID를 남깁니다.','서명 요청의 commitment를 실행 이전 블록에 기록합니다.'],fields:[['vault address','공동 보관과 거래의 온체인 주소'],['commitment / requestId','비공개 요청 해시와 중복 방지 키'],['Fill','실제 수량·금액·담보·lot'],['Withdrawal','실제로 지급된 토큰과 수신 지갑']]},
  {id:'market',name:'거래·차입',en:'Market / Venue',owns:'교환 가격, 토큰 교환, 차입 lot와 담보',input:'Vault의 매수·매도·차입매도·상환 호출',output:'Swap, ShortOpened, ShortClosed와 실제 토큰 이동',up:['vault'],down:['settlement'],implementation:'테스트 토큰 AMM·lot별 차입 구현',gap:'외부 상용 DEX 어댑터, 자동 청산·부족분 처리 정책은 미구현입니다. 부족한 전략 자금을 다른 전략에서 충당하지 않고 중단합니다.',source:'contracts/sleeves/OmnibusVault.sol · SleeveVenue',rules:['전략별 주문을 합성하거나 손익을 상계하지 않습니다.','같은 Vault·같은 자산이라도 차입 lot는 각각 관리합니다.','체결 수수료는 실제 받은 금액에 이미 포함됩니다.','슬리피지·기한·담보 부족 조건은 실패합니다.'],fields:[['reserves / quote','테스트 AMM 유동성과 교환 견적'],['amountIn / amountOut / fee','실제 교환 결과와 수수료 자산'],['lot / debt / escrow','차입 수량과 묶인 담보'],['deadline / limit','실행 제한 조건']]},
  {id:'settlement',name:'정산·검증',en:'Settlement / Reconciliation',owns:'영수증 확인, 손익·비용 귀속, 자산 대사, 보수 계산·지급 확인',input:'Vault·거래소 이벤트, 토큰 잔액, 차입·담보, 전략 귀속',output:'갱신된 전략 자산·투자자 권리·보수, 검증 기록',up:['vault','market'],down:['ledger','investor','provider'],implementation:'체결 귀속·대사·개별 환매·보수 지급 검증',gap:'독립 참여자의 forward track record는 아직 없습니다. 표시된 이력은 테스트 토큰 계약 실행 기록입니다.',source:'src/sleeves/runtime.js · event / reconcile / process',rules:['성공 영수증과 요청 ID·방향·자산·수량·한도를 대조합니다.','잔액과 장부가 다르면 이후 작업을 중단합니다.','전략 전체 포지션을 닫은 후 고점 초과 이익만 보수로 적립합니다.','보수 지급과 환매도 실제 토큰 전송을 확인합니다.'],fields:[['receipt / anchor','체결과 선행 commitment 영수증'],['claims / equity','정산 후 전략별·투자자별 권리'],['venueFees','원래 수수료 자산·수량. 중복 차감하지 않음'],['reconciliation','실제 보관액과 전략별 권리의 일치 결과']]},
  {id:'privacy',name:'비밀성·TEE 경계',en:'Privacy / Trust Boundary',owns:'제공자 → alpha → 전략 → 주문 → 체결 연결의 비공개성',input:'민감한 전략 데이터와 전략별 권리·주문 귀속',output:'외부에 필요한 최소 데이터와 검증 가능한 결과',up:['provider','ledger'],down:['authorization','vault'],implementation:'공개 응답·체인에서 귀속 분리 / TEE 제외',gap:'TEE, attestation, 운영자가 열람할 수 없는 저장·계산은 미구현입니다. 공유 주소가 통계적 추론 공격까지 막는다고 주장하지 않습니다.',source:'설계 경계 · docs/confidential-alpha-v0.2.md',rules:['목표: 민감 데이터와 전략 귀속은 TEE 안에서 처리합니다.','현재: 운영자 신뢰 프로세스와 비공개 로컬 파일을 사용합니다.','Vault 거래 자체를 숨기는 설계는 아닙니다.','이 검토 화면의 상세 장부는 로컬 테스트 데이터만 표시합니다.'],fields:[['보호 대상','alpha·포지션·투자자 권리·provider/order mapping'],['공개 대상','Vault 주소·토큰 이동·opaque 주문 ID'],['현재 신뢰 주체','운영자'],['미연결 경계','TEE 실행·attestation·키 보호']]}
];
export const flows = [
  {id:'register',name:'전략 등록',steps:[['provider','제공자가 독립 strategyId와 이름을 서명'],['authorization','등록 서명의 도메인·소유자·nonce 확인'],['ledger','전략 계정 생성; 자본·units는 0에서 시작']]},
  {id:'allocate',name:'투자·지분 발행',steps:[['investor','특정 전략과 금액을 선택하고 서명'],['authorization','소유자 확인, 요청 준비, 다른 변경 잠금'],['vault','투자자 지갑 → 공동 Vault 실제 예치'],['settlement','송신자·금액·요청 ID·확정 영수증 대조'],['ledger','해당 전략의 현재 지분가치로 units 발행'],['investor','선택한 전략에 대한 투자자 권리 반영']]},
  {id:'trade',name:'판단·주문·체결',steps:[['provider','private alpha → 전략별 목표·주문 (자동 변환 미구현)'],['authorization','현재 경로: 제공자가 서명한 주문의 소유권·한도 검사'],['ledger','해당 전략 자본만 사용; orderId 귀속 고정'],['vault','요청 해시 선행 기록 → 다음 블록에서 동일 주소로 실행'],['market','실제 교환 또는 lot별 차입·담보 처리'],['settlement','체결 이벤트와 토큰·부채 잔액 확인'],['ledger','실제 체결 수량·비용을 원래 전략에 반영']]},
  {id:'settle',name:'정산·보수',steps:[['provider','해당 전략의 포지션 종료 요청 서명'],['vault','정산 주문 전송'],['market','매도 / 매수 상환 → 담보 반환'],['settlement','전략 전체 정산 후 손익·고점·보수 계산'],['ledger','투자자 권리와 제공자 미지급 보수 분리'],['authorization','제공자 보수 지급 요청 권한 검사'],['vault','해당 보수 한도 안에서 실제 지급'],['settlement','지급 영수증 확인 후 미지급 보수 차감']]},
  {id:'redeem',name:'개별 환매',steps:[['investor','선택한 전략의 보유 지분에 대한 환매 서명'],['authorization','본인 지분·해당 전략의 포지션 정산 상태 검사'],['ledger','환매 가능 현금 계산; 다른 전략 지분은 유지'],['vault','투자자 지갑에 토큰 전송'],['settlement','동일 요청의 출금 영수증 확인'],['ledger','그 전략의 units와 현금만 차감']]},
  {id:'recovery',name:'실패·재시작',steps:[['authorization','외부 전송 전에 pending intent를 저장'],['vault','서명된 동일 거래 bytes / nonce / hash로 전송'],['settlement','미확정·실패·불일치이면 완료 처리하지 않음'],['authorization','재시작 시 기존 요청과 거래 해시를 재확인'],['ledger','확인된 효과를 한 번만 반영; 실패 원인 미해소 시 중단']]}
];
