import React,{useEffect,useState} from 'react';
import { BrowserProvider,Contract } from 'ethers';
import { canonicalJson } from '../shared/protocol.js';
const value=v=>Number(v||0)/1e6;
const cash=v=>v==null?'—':value(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const short=x=>x?x.slice(0,8)+'…'+x.slice(-6):'—';
export default function Strategies(){
  const [investor,setInvestor]=useState('a'),[state,setState]=useState(null),[selected,setSelected]=useState('btc-trend'),[amount,setAmount]=useState('10000'),[orderAmount,setOrderAmount]=useState('2500'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[evidence,setEvidence]=useState(null),[walletSigner,setWalletSigner]=useState(null),[newName,setNewName]=useState(''),[newDescription,setNewDescription]=useState('');
  async function request(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const j=await r.json();if(!r.ok)throw new Error(j.error);return j;}
  async function signed(signer,type,strategyId,data={}){const network=await signer.provider.getNetwork();if(Number(network.chainId)!==10143)throw new Error('지갑을 Monad 테스트넷(10143)으로 연결하세요.');const bytes=crypto.getRandomValues(new Uint8Array(32));const nonce='0x'+Array.from(bytes,x=>x.toString(16).padStart(2,'0')).join('');const payload={domain:'CONFIDENTIAL_ALPHA_V02',chainId:10143,vault:state.vault.address,signer:await signer.getAddress(),type,strategyId,data,nonce,expiresAt:Math.floor(Date.now()/1000)+300};return {payload,signature:await signer.signMessage(canonicalJson(payload))};}
  async function load(){if(walletSigner)setState(await request('/api/sleeves/execution/view',await signed(walletSigner,'VIEW','')));else {const s=await request('/api/sleeves/execution');setState(s.mode==='LOCAL_EVM'?await request('/api/sleeves/execution/local-fixture',{investor,action:'view'}):s);}}
  async function connect(){setError('');try{if(!window.ethereum)throw new Error('브라우저의 EVM 지갑 확장 프로그램이 필요합니다.');const provider=new BrowserProvider(window.ethereum);await provider.send('eth_requestAccounts',[]);const signer=await provider.getSigner();const e=await signed(signer,'VIEW','');setState(await request('/api/sleeves/execution/view',e));setWalletSigner(signer);}catch(e){setError(e.message);}}
  async function finishDeposit(pending){
    const signer=walletSigner;if(!signer||await signer.getAddress()!==pending.envelope.payload.signer)throw new Error('예치를 시작한 지갑으로 연결하세요.');
    const key='omnibus-pending-'+state.vault.address;
    if(!pending.transactionHash){
      const token=new Contract(pending.prepared.cash,['function approve(address,uint256) returns(bool)'],signer);await (await token.approve(state.vault.address,pending.prepared.amount)).wait();
      const vault=new Contract(state.vault.address,['function deposit(uint256,bytes32)'],signer);
      const tx=await vault.deposit(pending.prepared.amount,pending.prepared.id);pending.transactionHash=tx.hash;localStorage.setItem(key,JSON.stringify(pending));await tx.wait();
    }
    const result=await request('/api/sleeves/execution/complete',{envelope:pending.envelope,transactionHash:pending.transactionHash});localStorage.removeItem(key);return result;
  }
  async function resumeDeposit(){setBusy(true);setError('');try{const pending=JSON.parse(localStorage.getItem('omnibus-pending-'+state.vault.address));if(!pending)throw new Error('이 브라우저에 보관된 예치 요청이 없습니다.');await finishDeposit(pending);await load();setNotice('기존 예치 거래를 확인하고 전략 지분을 반영했습니다.');}catch(e){setError(e.message);}finally{setBusy(false);}}

  useEffect(()=>{let cancelled=false;setState(null);setError('');request('/api/sleeves/execution').then(async s=>s.mode==='LOCAL_EVM'?request('/api/sleeves/execution/local-fixture',{investor,action:'view'}):s).then(s=>{if(!cancelled)setState(s);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[investor]);
  useEffect(()=>{request('/api/sleeves/evidence').then(setEvidence).catch(()=>{});},[]);
  async function act(action,body={}){setBusy(true);setError('');setNotice('');try{let result;if(state.mode==='LOCAL_EVM')result=await request('/api/sleeves/execution/local-fixture',{investor,action,...body});else{
      if(!walletSigner)throw new Error('먼저 본인 지갑을 연결하세요.');
      const {strategyId,...data}=body,envelope=await signed(walletSigner,action,strategyId,data);
      if(action==='ALLOCATE'){const prepared=await request('/api/sleeves/execution/prepare',envelope),pending={envelope,prepared};localStorage.setItem('omnibus-pending-'+state.vault.address,JSON.stringify(pending));setState(previous=>({...previous,pending:true}));result=await finishDeposit(pending);}
      else result=await request('/api/sleeves/execution/submit',envelope);
    }await load();setNotice(result.registered?'제공자 서명을 확인하고 독립 전략을 등록했습니다.':'EVM 거래 확인 · '+result.transactionHash+' · 실제 토큰 잔액과 장부 일치');}catch(e){setError(e.message);}finally{setBusy(false);}}
  const strategy=state?.catalog.find(s=>s.id===selected);
  return <section className="strategy-market">
    <div className="card strategy-intro"><div><span className="eyebrow">MANY PRIVATE STRATEGIES · ONE SHARED VAULT</span><h2>전략은 선택하고, 자금은 함께 보관합니다.</h2><p>선택한 전략의 주문·비용·손익만 내 지분에 반영됩니다. 한 전략을 환매해도 다른 전략의 지분은 유지됩니다.</p></div><div className="strategy-review-label">실행 환경: {state?.mode==='MONAD_TESTNET'?'Monad 테스트넷':'로컬 EVM'} · 테스트 토큰 · TEE 미적용</div><p>{state?.mode==='MONAD_TESTNET'?'본인 지갑으로 요청을 서명합니다. 예치는 지갑이 직접 전송하고, 전략 주문과 환매는 서명을 확인한 운영자가 실행합니다. 테스트 토큰만 사용합니다.':'각 버튼은 서명 검증과 Solidity 계약 실행을 거칩니다. 테스트 계정의 서명은 로컬 서버가 생성합니다. 실제 지갑 로그인이나 실투자 화면은 아닙니다.'}</p><p><a href="/docs/confidential-alpha-v0.2.md" target="_blank" rel="noreferrer">제품 명세</a> · <a href="/docs/sleeves-v0.2.md" target="_blank" rel="noreferrer">구현·검증 범위</a></p></div>

    {error&&<div role="alert" className="alert error">{error}</div>}{notice&&<div role="status" className="alert" style={{overflowWrap:'anywhere'}}>{notice}</div>}
    {!state&&<p>계약 배포 또는 기존 EVM 거래 복구 중입니다…</p>}
    {state?.mode==='MONAD_TESTNET'?<div className="strategy-investor"><button className="primary" disabled={busy} onClick={connect}>지갑 연결·서명 인증</button><span>{short(state.investor)} · {cash(state.wallet)} tUSD</span>{state.pending&&<button className="secondary" disabled={busy||!walletSigner} onClick={resumeDeposit}>미완료 예치 계속</button>}</div>:<div className="strategy-investor"><label htmlFor="review-investor">로컬 테스트 지갑</label><select id="review-investor" value={investor} disabled={busy||!state} onChange={e=>setInvestor(e.target.value)}><option value="a">투자자 A</option><option value="b">투자자 B</option></select><span>{short(state?.investor)} · {cash(state?.wallet)} tUSD</span><button className="secondary" disabled={busy||!state} onClick={()=>load().catch(e=>setError(e.message))}>잔액 새로고침</button></div>}
    <div className="strategy-catalog" aria-label="전략 목록">{state?.catalog.map(s=><button key={s.id} disabled={busy} className={`card strategy-choice ${selected===s.id?'chosen':''}`} aria-pressed={selected===s.id} onClick={()=>setSelected(s.id)}><small>제공자 {short(s.provider)}</small><h3>{s.name}</h3><p>{s.description}</p><dl><div><dt>전략 지분당 가치</dt><dd>{value(s.unitPrice).toFixed(6)} tUSD</dd></div><div><dt>전략 투자자 자산</dt><dd>{cash(s.investorEquity)} tUSD</dd></div><div><dt>계약 정산 이력</dt><dd>{s.settledRounds}회</dd></div></dl><span>테스트 자산 실행 이력 · 실전 성과 아님</span></button>)}</div>
    {strategy&&<div className="card"><div className="card-heading"><div><h2>{strategy.name}에 배정</h2><p>내 지갑에서 공동 Vault로 테스트 토큰을 보내고, 이 전략의 지분을 받습니다.</p></div></div><form className="strategy-allocate" onSubmit={e=>{e.preventDefault();act('ALLOCATE',{strategyId:selected,amount});}}><label htmlFor="allocation-amount">배정 금액 (tUSD)</label><input id="allocation-amount" type="number" min="0.000001" step="0.000001" value={amount} required onChange={e=>setAmount(e.target.value)}/><button className="primary" disabled={busy}>서명·예치·전략 배정</button></form><p className="subtle-caption">포지션 정산 후 입출금합니다. 해당 전략의 이전 지분가치 고점을 넘는 이익의 {strategy.feeBps/100}%를 제공자 보수로 적립합니다.</p></div>}
    <div className="card"><h2>내가 선택한 전략</h2>{state?.portfolio.length?<div className="table-scroll"><table className="pilot-table"><thead><tr><th>전략</th><th>내 지분</th><th>현재 내 권리</th><th>환매</th></tr></thead><tbody>{state.portfolio.map(p=><tr key={p.strategyId}><td>{p.name}</td><td>{value(p.units).toLocaleString('en-US',{maximumFractionDigits:6})}</td><td>{cash(p.claim)} tUSD</td><td><button className="secondary" disabled={busy||!p.canRedeem} onClick={()=>act('REDEEM',{strategyId:p.strategyId})}>{p.canRedeem?'이 전략만 환매':'포지션 정산 필요'}</button></td></tr>)}</tbody></table></div>:<p>원하는 전략을 선택해 자본을 배정하세요.</p>}</div>
    {strategy&&selected!=='cash-reserve'&&<details className="card" open><summary>제공자 실행 검토 · {strategy.name}</summary><p>{state?.mode==='MONAD_TESTNET'?'연결된 지갑이 해당 전략의 제공자일 때만 주문을 받습니다.':'선택한 전략 제공자의 테스트 키로 주문을 서명합니다.'} 서명한 주문의 해시를 먼저 계약에 기록하고, 다음 블록에서 같은 Vault로 실행합니다. 신규 주문 한도는 이 전략 투자자 자산의 25%입니다.</p><div className="strategy-allocate"><label htmlFor="order-amount">매수 자금 / 숏 담보 (tUSD)</label><input id="order-amount" type="number" min="0.000001" step="0.000001" value={orderAmount} onChange={e=>setOrderAmount(e.target.value)}/><button className="primary" disabled={busy} onClick={()=>act('ORDER',{strategyId:selected,side:selected==='btc-hedge'?'SHORT_OPEN':'BUY',amount:orderAmount})}>{selected==='btc-hedge'?'서명·차입·매도':'서명·BTC 매수'}</button><button className="secondary" disabled={busy} onClick={()=>act('ORDER',{strategyId:selected,side:selected==='btc-hedge'?'SHORT_CLOSE':'SELL'})}>이 전략 포지션 정산</button><button className="secondary" disabled={busy||!BigInt(strategy.providerAccrual)} onClick={()=>act('PAY_PROVIDER',{strategyId:selected})}>제공자 보수 지급 ({cash(strategy.providerAccrual)})</button></div><p>가격 상승 버튼은 없습니다. AMM 계약의 실제 토큰 교환 결과로 체결 금액과 비용이 결정됩니다.</p></details>}
    {state?.mode==='MONAD_TESTNET'&&<details className="card"><summary>제공자로 전략 등록</summary><p>연결한 지갑을 제공자로 등록합니다. 이 전략에 배정된 자본만 운용할 수 있습니다.</p><form className="strategy-allocate" onSubmit={e=>{e.preventDefault();act('REGISTER',{strategyId:'strategy-'+crypto.randomUUID().slice(0,8),name:newName,description:newDescription});}}><input aria-label="전략 이름" required maxLength={100} value={newName} onChange={e=>setNewName(e.target.value)} placeholder="전략 이름"/><input aria-label="전략 설명" maxLength={500} value={newDescription} onChange={e=>setNewDescription(e.target.value)} placeholder="전략 설명"/><button className="primary" disabled={busy||!walletSigner}>서명·전략 등록</button></form></details>}
    <details className="card strategy-accounting"><summary>공동 Vault 자산과 전략별 권리 대사</summary><p style={{overflowWrap:'anywhere'}}>Vault {state?.vault.address}</p><dl><div><dt>실제 토큰·담보·차입 평가액</dt><dd>{cash(state?.vault.vaultEquity)} tUSD</dd></div><div><dt>전략 자산가치 합계</dt><dd>{cash(state?.vault.strategyEquity)} tUSD</dd></div><div><dt>프로토콜 귀속·반올림</dt><dd>{cash(state?.vault.protocolAccrual)} tUSD</dd></div><div><dt>잔액 대사</dt><dd>{state?.vault.balanced?'일치':'대기'}</dd></div></dl><p>공동 Vault의 총액은 투자 수익률이 아닙니다. 거래 영수증과 토큰 잔액이 장부와 맞지 않으면 다음 작업을 중단합니다.</p></details>
    <details className="card"><summary>내 입출금 거래 영수증 ({state?.receipts.length||0})</summary><div className="table-scroll"><table className="pilot-table"><thead><tr><th>작업</th><th>전략</th><th>블록</th><th>거래 해시</th></tr></thead><tbody>{state?.receipts.map(r=><tr key={r.hash}><td>{r.type}</td><td>{r.strategyId}</td><td>{r.block}</td><td title={r.hash}>{short(r.hash)}</td></tr>)}</tbody></table></div></details>
    {evidence?.available&&<div className="card"><h2>Monad 테스트넷 실행 증거</h2><p>별도 배포된 공동 Vault에서 전략별 거래와 환매를 검증했습니다. 아래 조작 화면은 이 테스트넷 자금을 사용하지 않습니다.</p><p>Vault <a href={'https://testnet.monadexplorer.com/address/'+evidence.vault} target="_blank" rel="noreferrer">{evidence.vault}</a></p><p>확인된 작업 {evidence.operations}건 · 최종 장부 {evidence.balanced?'일치':'확인 필요'} · 테스트 계정과 테스트 자산 사용</p><details><summary>작업별 테스트넷 거래 보기</summary><div className="table-scroll"><table className="pilot-table"><thead><tr><th>작업</th><th>전략</th><th>체인 거래</th></tr></thead><tbody>{evidence.transactions.map(t=><tr key={t.hash}><td>{t.type}</td><td>{t.strategyId}</td><td><a href={'https://testnet.monadexplorer.com/tx/'+t.hash} target="_blank" rel="noreferrer">{short(t.hash)}</a></td></tr>)}</tbody></table></div></details></div>}
  </section>;
}
