import React,{useEffect,useState} from 'react';
const value=v=>Number(v||0)/1e6;
const cash=v=>value(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function Strategies(){
  const [investor,setInvestor]=useState('review-a'),[state,setState]=useState(null),[selected,setSelected]=useState('btc-trend'),[amount,setAmount]=useState('10000'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function request(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const j=await r.json();if(!r.ok)throw new Error(j.error);return j;}
  async function load(){setState(await request('/api/sleeves/review?investor='+investor));}
  useEffect(()=>{let cancelled=false;setState(null);request('/api/sleeves/review?investor='+investor).then(s=>{if(!cancelled)setState(s);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[investor]);
  async function act(action,body){setBusy(true);setError('');try{await request('/api/sleeves/review/'+action,{...body,requestId:crypto.randomUUID()});await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  const strategy=state?.catalog.find(s=>s.id===selected);
  return <section className="strategy-market">
    <div className="card strategy-intro"><div><span className="eyebrow">CONCEPT V0.2 · MANY STRATEGIES, ONE VAULT</span><h2>투자할 전략을 직접 선택하세요.</h2><p>자금은 하나의 Vault에 보관하고, 지분과 손익은 선택한 전략에 각각 귀속합니다.</p></div><div className="strategy-review-label">격리된 회계 검토 환경 · 실제 투자 아님</div><p>{state?.explanation||'전략별 장부를 불러오는 중입니다.'}</p><p><a href="/docs/confidential-alpha-v0.2.md" target="_blank" rel="noreferrer">승인된 제품 명세</a> · <a href="/docs/sleeves-v0.2.md" target="_blank" rel="noreferrer">새 구현 범위와 남은 연결</a></p></div>
    {error&&<div role="alert" className="alert error">{error}</div>}
    <div className="strategy-investor"><label htmlFor="review-investor">검토용 투자자</label><select id="review-investor" value={investor} disabled={busy} onChange={e=>setInvestor(e.target.value)}><option value="review-a">투자자 A</option><option value="review-b">투자자 B</option></select><span>검토 지갑: {cash(state?.wallet)} tUSD</span><small>이 선택은 로그인이나 실제 지갑 연결이 아닙니다.</small></div>
    <div className="strategy-catalog" aria-label="전략 목록">{state?.catalog.map(s=><button key={s.id} className={`card strategy-choice ${selected===s.id?'chosen':''}`} aria-pressed={selected===s.id} onClick={()=>setSelected(s.id)}><small>{s.provider}</small><h3>{s.name}</h3><p>{s.description}</p><dl><div><dt>전략 지분당 가치</dt><dd>{value(s.unitPrice).toFixed(6)} tUSD</dd></div><div><dt>전략 투자자 자산</dt><dd>{cash(s.investorEquity)} tUSD</dd></div><div><dt>검토 회차</dt><dd>{s.history.length}회</dd></div></dl><span>실제 forward 이력 없음 · 회계 검토 예제</span></button>)}</div>
    {strategy&&<div className="card"><div className="card-heading"><div><h2>{strategy.name}에 자본 배정</h2><p>이 전략의 지분을 받습니다. 다른 전략의 수익이나 손실을 공유하지 않습니다.</p></div></div><form className="strategy-allocate" onSubmit={e=>{e.preventDefault();act('allocate',{investor,strategyId:selected,amount});}}><label htmlFor="allocation-amount">배정 금액 (검토 tUSD)</label><input id="allocation-amount" type="number" min="0.000001" step="0.000001" value={amount} required onChange={e=>setAmount(e.target.value)}/><button className="primary" disabled={busy}>선택한 전략에 배정</button></form><p className="subtle-caption">검토 정책: 각 전략의 지분당 이전 고점을 넘는 이익의 {strategy.feeBps/100}%를 해당 전략 제공자 보수로 적립합니다. 전체 Vault 이익으로 배분하지 않습니다.</p></div>}
    <div className="card"><div className="card-heading"><div><h2>내가 선택한 전략</h2><p>각 행은 독립적인 투자 지분입니다.</p></div></div>{state?.portfolio.length?<div className="table-scroll"><table className="pilot-table"><thead><tr><th>전략</th><th>내 지분 수</th><th>현재 내 권리</th><th>자본 회수</th></tr></thead><tbody>{state.portfolio.map(p=><tr key={p.strategyId}><td>{p.name}</td><td>{value(p.units).toLocaleString('en-US',{maximumFractionDigits:6})}</td><td>{cash(p.claim)} tUSD</td><td><button className="secondary" disabled={busy} onClick={()=>act('redeem',{investor,strategyId:p.strategyId})}>이 전략만 환매</button></td></tr>)}</tbody></table></div>:<p>아직 배정한 전략이 없습니다. 위에서 원하는 전략을 선택하세요.</p>}</div>
    <details className="card strategy-accounting"><summary>공동 보관 장부 대사 · 투자 상품 수익률과 별도</summary><dl><div><dt>공동 Vault 자산가치</dt><dd>{cash(state?.vault.vaultEquity)} tUSD</dd></div><div><dt>전략별 자산가치 합</dt><dd>{cash(state?.vault.strategyEquity)} tUSD</dd></div><div><dt>프로토콜 귀속 및 평가 반올림</dt><dd>{cash(state?.vault.protocolAccrual)} tUSD</dd></div><div><dt>대사 결과</dt><dd>{state?.vault.balanced?'일치':'대기'}</dd></div></dl><p>전략 자산가치에는 해당 전략의 투자자 권리와 제공자 미지급 보수를 포함합니다. 주문과 전략의 연결은 공개 응답에서 제외합니다.</p></details>
    <div className="card"><h2>두 전략이 섞이지 않는지 확인</h2><p>상승 전략과 하락 전략에 각각 배정한 후 아래 검토를 실행하면, 같은 가격 변화에 대해 서로 다른 지분가치가 계산됩니다. 통제한 가격과 모의 체결을 사용하며 기존 Monad 계약으로 거래를 보내지 않습니다.</p><div className="pilot-actions"><button className="secondary" disabled={busy||!state} onClick={()=>act('cycle',{moveBps:1000})}>BTC +10% 회계 검토</button><button className="secondary" disabled={busy||!state} onClick={()=>act('cycle',{moveBps:-1000})}>BTC −10% 회계 검토</button></div></div>
  </section>;
}
